# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ajedrez_GUI_qt.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from QPyQt5Canvas import QPyQt5Canvas


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(623, 606)
        self.canvas = QPyQt5Canvas(Form)
        self.canvas.setGeometry(QtCore.QRect(50, 80, 400, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setObjectName("canvas")
        self.TextoMulti = QtWidgets.QLabel(Form)
        self.TextoMulti.setGeometry(QtCore.QRect(50, 10, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TextoMulti.setFont(font)
        self.TextoMulti.setTextFormat(QtCore.Qt.PlainText)
        self.TextoMulti.setAlignment(QtCore.Qt.AlignCenter)
        self.TextoMulti.setWordWrap(True)
        self.TextoMulti.setObjectName("TextoMulti")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(280, 510, 138, 50))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Movimientos_List = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Movimientos_List.setFont(font)
        self.Movimientos_List.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Movimientos_List.setObjectName("Movimientos_List")
        self.verticalLayout_2.addWidget(self.Movimientos_List)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(60, 490, 169, 100))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.PosIn_LineEdit = QtWidgets.QLineEdit(self.widget1)
        self.PosIn_LineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PosIn_LineEdit.setFont(font)
        self.PosIn_LineEdit.setText("")
        self.PosIn_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.PosIn_LineEdit.setObjectName("PosIn_LineEdit")
        self.verticalLayout.addWidget(self.PosIn_LineEdit)
        self.MoverPieza_Button = QtWidgets.QPushButton(self.widget1)
        self.MoverPieza_Button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.MoverPieza_Button.setFont(font)
        self.MoverPieza_Button.setObjectName("MoverPieza_Button")
        self.verticalLayout.addWidget(self.MoverPieza_Button)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(461, 141, 151, 60))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Iniciar_Button = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Iniciar_Button.sizePolicy().hasHeightForWidth())
        self.Iniciar_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Iniciar_Button.setFont(font)
        self.Iniciar_Button.setObjectName("Iniciar_Button")
        self.verticalLayout_3.addWidget(self.Iniciar_Button)
        self.Salir_Button = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Salir_Button.setFont(font)
        self.Salir_Button.setObjectName("Salir_Button")
        self.verticalLayout_3.addWidget(self.Salir_Button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TextoMulti.setText(_translate("Form", "Bienvenido a nuestro ajedrez. Presionar \"Iniciar juego\" para empezar"))
        self.label_3.setText(_translate("Form", "Movimientos posibles"))
        self.label_2.setText(_translate("Form", "Posición de pieza a mover"))
        self.MoverPieza_Button.setText(_translate("Form", "Generar movimientos"))
        self.Iniciar_Button.setText(_translate("Form", "Iniciar juego"))
        self.Salir_Button.setText(_translate("Form", "Salir"))
